services:
  orientation:
    build: .
    ports:
      - "8088:8088"
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_container
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_container
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    devices:
      - "/dev/dri"
      - "/dev/kfd"
    group_add:
      - "44"
      - "993"
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - OLLAMA_VULKAN=1
      - OLLAMA_IGPU_ENABLE=1
      - OLLAMA_NUMA=1
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_KV_CACHE_TYPE=q4_0
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_KEEP_ALIVE=-1
        #- OLLAMA_CONTEXT_LENGTH=8192
        #- HSA_OVERRIDE_GFX_VERSION=11.0.0
        #- GGML_VK_DISABLE_INTEGER_DOT_PRODUCT=1
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_container
    privileged: true
    group_add:
      - "988"
    ports:
      - "5678:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_COOKIE_HTTP_ONLY=true
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=http://192.168.2.31:5678/
      - N8N_RESTRICT_FILE_ACCESS_TO=/home/node/.n8n-files;/home/ralf/n8n-ki-system/n8n_files
      # - NODE_FUNCTION_ALLOW_EXTERNAL=pdf-parse
      - NODES_EXCLUDE=[]
      - N8N_RUNNERS_ENABLED=false
      - N8N_RUNNERS_MODE=internal
      - N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES=false

    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./n8n_files:/home/node/.n8n-files
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    restart: unless-stopped
    depends_on:
      - qdrant
      - ollama
